# ----
# Site

title: FunkeMT
url: "https://funkemt.github.io"
baseurl:
google_analytics_key:
show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: FunkeMT Own Wiki.
author:
  name: Markus Funke
  email: funkemarkus@me.com
  twitter: # twitter username without the @ symbol
social:
  name: Markus Funke
  links:
    - https://github.com/FunkeMT
    - https://www.xing.com/profile/Markus_Funke25
    - https://medium.com/@FunkeMT

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true
  glossary:
    title: Glossary
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
